// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ListPetsData, ListPetsResponses, ListPetsErrors, CreatePetsData, CreatePetsResponses, CreatePetsErrors, ShowPetByIdData, ShowPetByIdResponses, ShowPetByIdErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all pets
 */
export const listPets = <ThrowOnError extends boolean = false>(options?: Options<ListPetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListPetsResponses, ListPetsErrors, ThrowOnError>({
        url: '/pets',
        ...options
    });
};

/**
 * Create a pet
 */
export const createPets = <ThrowOnError extends boolean = false>(options?: Options<CreatePetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreatePetsResponses, CreatePetsErrors, ThrowOnError>({
        url: '/pets',
        ...options
    });
};

/**
 * Info for a specific pet
 */
export const showPetById = <ThrowOnError extends boolean = false>(options: Options<ShowPetByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ShowPetByIdResponses, ShowPetByIdErrors, ThrowOnError>({
        url: '/pets/{petId}',
        ...options
    });
};