// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPet = z.object({
    id: z.coerce.bigint(),
    name: z.string(),
    tag: z.string().optional()
});

export const zPets = z.array(zPet);

export const zError = z.object({
    code: z.number().int(),
    message: z.string()
});

/**
 * How many items to return at one time (max 100)
 */
export const zListPetsParameterLimit = z.number().int();

/**
 * A paged array of pets
 */
export const zListPetsResponse = zPets;

/**
 * The id of the pet to retrieve
 */
export const zShowPetByIdParameterPetId = z.string();

/**
 * Expected response to a valid request
 */
export const zShowPetByIdResponse = zPet;